### ISSUE TITLE
BUG - icons .svg files not found with pip install

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/bg-brainrender-gui#2]
as per [this comment](https://github.com/brainglobe/bg-brainrender-gui/issues/1#issuecomment-667210079) the `.svg` files with the app's icons files are not packaged with the rest of the code. 

@adamltyson  I thought I had set up correctly, but I seemed to have missed this. Would you mind having a look when you have a chance?

**Comment by adamltyson** [comment]
Hey @FedeClaudi. 

Sorry for the delay. I think the `.svg` files are packaged correctly, but the issue lies in how they are referenced. Looking at @horsto's error report, the GUI isn't looking for the icon images in the correct place. It seems to be relative to the current working directory:

https://github.com/brainglobe/bg-brainrender-gui/blob/d8ec35c61cfcbd2b979f029a009007aef4245590/brainrender_gui/widgets/actors_list.py#L26


The way I get around this is to do something like:
```python
from pkg_resources import resource_filename
item.setIcon(QIcon(resource_filename("brainrender_gui", "icons/eye.svg")))
```

**Comment by FedeClaudi** [comment]
Thanks!

Should be fixed with 488dbf46395b6ad563b6fa78222d1ec70bbd5a50 [release version `0.0.4`].

**Comment by horsto** [comment]
![Screenshot 2020-08-15 at 12 41 39](https://user-images.githubusercontent.com/7548928/90310738-b2b7d500-def4-11ea-87ee-d83daa00301d.png)
Although the warning / error message disappeared, the GUI still doesn't have a system icon (macOS Catalina, `bg-brainrender-gui-0.0.4`)

**Comment by FedeClaudi** [comment]
Hi, 

The bug was relative to icons used within the application, not the system icon (which could be nice to add though).
After the fix, in the `actors list` you should see an `eye` icon next to the actors that are being visualized (and a different icon when an actor is hidden following double click on the actor's name in the list)

<img width="376" alt="image" src="https://user-images.githubusercontent.com/17436313/90311277-1c35e480-def1-11ea-81e4-50a54fe0f5b5.png">

**Comment by horsto** [comment]
Yes, I see that icon :ok_hand:

**Comment by FedeClaudi** [comment]
I've added the system icon: 
<img width="157" alt="image" src="https://user-images.githubusercontent.com/17436313/90317597-8b77fc80-df22-11ea-944f-b5be519da39e.png">

thanks for the idea @horsto

**Comment by horsto** [comment]
ha, that looks awesome.
